version: "3"

services:
  web:
    container_name: emp_service_web
    # build: .
    # image: emp_service
    image: abhigyani/emp_service:0.0.0
    ports:
      - "80:80"
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - path: .env
        required: true

  mysql_db:
    container_name: emp_service_db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOTPASSWORD}
      MYSQL_DATABASE_PORT: ${MYSQL_DB_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  default:
    name: emp_svc_network
